name: 'Setup smalltalkCI'
description: 'Set up smalltalkCI for testing Squeak/Smalltalk, Pharo, GemStone,
  and Moose projects'
author: 'Software Architecture Group, Hasso Plattner Institute'
inputs:
  smalltalk-image:
    description: 'Smalltalk image selection (see smalltalkCI''s list of
      supported images)'
  smalltalk-version:
    description: 'Deprecated, please use smalltalk-image'
  smalltalkCI-source:
    description: 'GitHub slug of the smalltalkCI source repository'
    required: false
    default: 'hpi-swa/smalltalkCI'
  smalltalkCI-branch:
    description: 'Branch or tag to use from smalltalkCI repository'
    required: false
    default: 'master'
outputs:
  smalltalk-image:
    description: 'Smalltalk image selection'
  smalltalk-version:
    description: 'Deprecated, please use smalltalk-image'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'blue'
